services:

    app_bundle.block.header_formatter:
        class: Brother\CMSBundle\Block\HeaderFormatterBlock
        tags: [ { name: "sonata.block" } ]
        arguments: [ ~, @templating ]

    sonata.page.service.user_type:
        class:      "%sonata.page.service.default.class%"
        tags:       [{ name: "sonata.page" }]
        arguments:  [ 'user_type', @sonata.page.template_manager, @sonata.seo.page ]

    cms.bundle.block.breadcrumb:
        class: "Brother\CMSBundle\Block\CMSBreadcrumbBlockService"
        tags: [{ name: "sonata.block" }, {name: "sonata.breadcrumb"}]
        arguments: ['cms_breadcrumbs', cms.bundle.block.breadcrumb, @templating, @knp_menu.menu_provider, @knp_menu.factory]
