<?php
/**
 * This file is part of the <name> project.
 *
 * (c) brother79
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Brother\CMSBundle\Entity\Media;

use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author brother79
 */
class Gallery extends BaseGallery
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getImages($limit = 0)
    {
        if ($limit) {
//            AppDebug::_dx(get_class($this->galleryHasMedias->getValues()));
            return array_slice($this->galleryHasMedias->getValues(), 0, $limit);
        } else {
            return $this->galleryHasMedias;
        }
    }

    public function getImages4()
    {
        return $this->getImages(4);
    }
}